return {
	  { "nvim-treesitter/nvim-treesitter", version = "0.9.1" },

	  { "akinsho/bufferline.nvim", version = "4.4.0" },
	  { "folke/flash.nvim", version = "1.18.2" },
	  { "folke/lazy.nvim", version = "10.14.6" },
	  { "LazyVim/LazyVim", version = "10.4.4" },
	  { "echasnovski/mini.ai", version = "0.10.0" },
	  { "echasnovski/mini.comment", version = "0.10.0" },
	  { "echasnovski/mini.pairs", version = "0.10.0" },
	  { "echasnovski/mini.bufremove", version = "0.10.0" },
	  { "echasnovski/mini.indentscope", version = "0.10.0" },
	  { "echasnovski/mini.surround", version = "0.10.0" },
	  { "rcarriga/nvim-notify", version = "3.12.0" },
	  { "folke/persistence.nvim", version = "2.0.0" },
	  { "nvim-lua/plenary.nvim", version = "0.1.4" },
	  { "folke/tokyonight.nvim", version = "2.9.0" },
	  { "folke/which-key.nvim", version = "1.6.0" },
	  { "catppuccin/nvim", version = "1.5.0" },
	  { "stevearc/conform.nvim", version = "4.0.0" },
	  { "stevearc/dressing.nvim", version = "2.0.1" },
	  { "lewis6991/gitsigns.nvim", version = "0.6" },
	  { "lukas-reineke/indent-blankline.nvim", version = "3.3.2" },
	  { "L3MON4D3/LuaSnip", version = "2.0.0" },
	  { "williamboman/mason-lspconfig.nvim", version = "1.18.0" },
	  { "williamboman/mason.nvim", version = "1.8.1" },
	  { "folke/neoconf.nvim", version = "1.2.2" },
	  { "folke/neodev.nvim", version = "2.5.2" },
	  { "neovim/nvim-lspconfig", commit = "e49b1e9" },
	  { "folke/todo-comments.nvim", version = "1.1.0" },
	  { "folke/trouble.nvim", version = "2.10.0" },
	  { "dstein64/vim-startuptime", version = "4.4.0" },

	  { "nvim-telescope/telescope.nvim", tag = "0.1.4" },
	  { "MunifTanjim/nui.nvim", tag = "0.2.0" },
	  { "nvim-lualine/lualine.nvim", tag = "compat-nvim-0.6" },
	  { "nvim-neo-tree/neo-tree.nvim", tag = "3.8" },
	  { "nvim-treesitter/nvim-treesitter-context", tag = "compat/0.7" },
	  { "nvim-tree/nvim-web-devicons", tag = "nerd-v2-compat" },

	  { "nvimdev/dashboard-nvim", commit = "416f12e" },
	  { "folke/noice.nvim", commit = "e50fc6d" },
	  { "nvim-treesitter/nvim-treesitter-textobjects", commit = "78c49ca" },
	  { "nvim-telescope/telescope-fzf-native.nvim", commit = "6c921ca" },
	  { "hrsh7th/cmp-buffer", commit = "3022dbc" },
	  { "hrsh7th/cmp-nvim-lsp", commit = "44b16d1" },
	  { "hrsh7th/cmp-path", commit = "584414b" },
	  { "saadparwaiz1/cmp_luasnip", commit = "05a9ab2" },
	  { "rafamadriz/friendly-snippets", commit = "43727c2" },
	  { "hrsh7th/nvim-cmp", commit = "d3a3056" },
	  { "mfussenegger/nvim-lint", commit = "7c8b50a" },
	  { "nvim-pack/nvim-spectre", commit = "696cff7" },
	  { "windwp/nvim-ts-autotag", commit = "6be1192" },
	  { "JoosepAlviste/nvim-ts-context-commentstring", commit = "92e688f" },
	  { "RRethy/vim-illuminate", commit = "3bd2ab6" },
}
